disabled_rules: # rule identifiers to exclude from running
    - line_length
    - todo
    - identifier_name
    - type_name
    - function_body_length
    - type_body_length
    - force_try
    - cyclomatic_complexity
    - function_parameter_count
    - vertical_whitespace
    - empty_parentheses_with_trailing_closure
    - trailing_comma
    - unused_closure_parameter
    - vertical_parameter_alignment
    - syntactic_sugar
    - redundant_optional_initialization
    - unused_optional_binding
    - redundant_string_enum_value
    - for_where
    - shorthand_operator
    - large_tuple
    - fallthrough
opt_in_rules:
    - empty_count
included:
    - pnutAPI
